name: Check Cairo Smart Contracts
on:
  push:
jobs:
  check-cairo-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Cairo formatting
        uses: milancermak/cairo-format-action@v1
      - name: Check Cairo contract interface consistency
        uses: 42labs/starknet-interface-checker-gha@main
        with:
          cairo-path: contracts/src
